### PR TITLE
Clustering jun15

### PR DESCRIPTION
**Pull request by cwalker7**
Updated the clustering function in foldamers/ensembles/cluster.py to use kmeans from scikit-learn instead of msmbuilder kcenters, and added example of its use. The following data is returned after clustering:
- Medoid (closest structure within the trajectory set) pdb for each cluster
- Centroid (average structure) pdb for each cluster - not physically relevant. Do we care about this?
- List of sizes of each cluster
- RMSD in cluster distance space for each cluster
The example files are from a 48 replica simulation - we can get rid of these eventually but it would be useful to test different clustering methods on the same data.

### CODE REVIEW

**Comment by mrshirts** [comment]
> but it would be useful to test different clustering methods on the same data.

Agreed. Eventually, once we have a couple of good foldamer parameters, we should have a database with 1-2 runs, and all the example scripts just analyze those.

* We probably want to separate the script that does the running from the script that does the analysis.  What do you think about separating the two functionalities here, exporting the CG model, and then having a separate script that actually does the analysis with the list of pdb files and (reloaded) cg model?

* Should the analysis work on pdb files, or directly on the .nc file? I guess we want to be able cluster simulations from multiple runs that AREN'T the same replica exchange file, so doing it through PDB files is OK for now.

* We should consider whether there should be wrapper functions that take structures (in whatever format they are) and loads them in to mdtraj trajectories, and then another one that actually does the clustering, but that can be done as a separate step if there are more important things to do first.

* This can also be done after, but you could consider adding silhouette analysis https://scikit-learn.org/stable/auto_examples/cluster/plot_kmeans_silhouette_analysis.html to look at the number of clusters.

**Comment by cwalker7** [comment]
- Yeah, this is a great case for loading the stored cgmodel. I can separate out the running the simulation, and have a script that just loads in the cgmodel and does the clustering.

- As for the input files, I think it's a good idea to eventually support both .nc and pdb.

- I will look into adding the silhouette analysis, shouldn't be too hard

**Comment by mrshirts** [comment]
You probably want to change it to merge into `master` instead of `new_cv`, since it includes a number of changes already merged into master that were not merged into `new_cv`.  That can be toggled with the `edit` button to the far right of the PR title.

**Comment by cwalker7** [comment]
Yeah good catch! Just want to fix that temperature list issue here too, so we can merge after that.

**Comment by cwalker7** [comment]
This should be good now, shall I merge? I think we can eventually combine calc_temperature_spacing and get_temperature_list in reweight.py to a simpler function, but the extra replica issue is fixed now.

The silhouetting analysis I can add later.

**Comment by mrshirts** [comment]
Go ahead and merge, though file the issue about rewriting the two functions in an issue before you forget.

In the future, we probably should not have too many run_replica_exchage.py scripts (maybe just one per repository, and then read from the same model in the analysis script, though that isn't high priority now.

**Pull request merged**
